@baseUrl = http://localhost:8080

@name = João Victor

@email = joao.victor@example.com

@username = joaovictor

@password = secret123

### Registro do usuário

POST {{baseUrl}}/api/auth/register 
Content-Type: application/json

{
    "name": "{{name}}",
    "email": "{{email}}",
    "username": "{{username}}",
    "password": "{{password}}"
}

### Login com username

POST {{baseUrl}}/api/auth/login 
Content-Type: application/json

{
    "identifier": "{{username}}",
    "password": "{{password}}"
}

### OU login com email

POST {{baseUrl}}/api/auth/login 
Content-Type: application/json

{
  "identifier": "{{email}}",
  "password": "{{password}}"
}

# ⚠️ Após o login, copie o token da resposta e cole abaixo:
@token = cole_o_token_aqui
@userId = cole_o_id_do_usuario_se_quiser

### Buscar todos os usuários

GET {{baseUrl}}/api/users 
Authorization: Bearer {{token}}

### Buscar usuário por ID

GET {{baseUrl}}/api/users/{{userId}} 
Authorization: Bearer {{token}}

### Deletar usuário por ID

DELETE {{baseUrl}}/